STATUS_OK = 200
STATUS_NOT_FOUND = 404
STATUS_INTERNAL_SERVER_ERROR = 500

HTTP_STATUS_MESSAGE = {
    STATUS_OK: f"{str(STATUS_OK)} OK.",
    STATUS_NOT_FOUND: f"{str(STATUS_NOT_FOUND)} File Not Found.",
    STATUS_INTERNAL_SERVER_ERROR: f"{str(STATUS_INTERNAL_SERVER_ERROR)} Internal Server Error.",
}

DEFAULT_DOCUMENT = "/index.html"
NOT_FOUND_DOCUMENT = "/404.html"
