STATUS_OK = 200
STATUS_NOT_FOUND = 404
STATUS_INTERNAL_SERVER_ERROR = 500

HTTP_STATUS_MESSAGE = {
    STATUS_OK: "OK.",
    STATUS_NOT_FOUND: "File Not Found.",
    STATUS_INTERNAL_SERVER_ERROR: "Internal Server Error.",
}

NOT_FOUND_FILE = "/404.html"
